name: liqo

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    name: 🚀 Deploy to FTP
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 151.243.222.70
        username: liqo@zakkal.my.id
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21
        security: loose
        timeout: 60000
        exclude: |
          **/.git*
          **/vendor/**
          **/node_modules/**
          **/.github/**
